print('======EX003======')
n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
print(f'A soma entre {n1} e {n2} é {n1 + n2}')

print('======EX004======')
n = input('Digite um valor: ')
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isupper())
print(n.islower())
print(n.isspace())
print(n.isidentifier())