print('======EX004======')
n = input('Digite um valor: ')
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isupper())
print(n.islower())
print(n.isspace())
print(n.isidentifier())